### ISSUE TITLE
Fails when importing an SVG

### ISSUE THREAD

**Issue by gugahoi** [steveswork/ordercss#2]
Unfortunately the tool doesn't seem to be able to handle `svg` imports:

```
ENOTDIR: not a directory, open '[REDACTED]/frontend/src/images/logo.svg/index.js'
```

The file is simply under the `logo.svg` import but for some reason `ordercss` is interpreting this as a directory.

## Stacktrace

```
Error: ENOTDIR: not a directory, open '[REDACTED]/frontend/src/images/logo.svg/index.js'
    at Object.openSync (fs.js:476:3)
    at readFileSync (fs.js:377:35)
    at /Users/guga/.nvm/versions/node/v14.15.0/lib/node_modules/@webkrafters/ordercss/src/order-imports/index.js:78:11
    at pullJsDependencyPaths (/Users/guga/.nvm/versions/node/v14.15.0/lib/node_modules/@webkrafters/ordercss/src/order-imports/index.js:205:33)
    at buildImportGraphInto (/Users/guga/.nvm/versions/node/v14.15.0/lib/node_modules/@webkrafters/ordercss/src/order-imports/index.js:304:6)
    at buildImportGraphInto (/Users/guga/.nvm/versions/node/v14.15.0/lib/node_modules/@webkrafters/ordercss/src/order-imports/index.js:321:19)
    at buildImportGraphInto (/Users/guga/.nvm/versions/node/v14.15.0/lib/node_modules/@webkrafters/ordercss/src/order-imports/index.js:321:19)
    at inspectModule (/Users/guga/.nvm/versions/node/v14.15.0/lib/node_modules/@webkrafters/ordercss/src/order-imports/index.js:344:2)
    at /Users/guga/.nvm/versions/node/v14.15.0/lib/node_modules/@webkrafters/ordercss/src/order-imports/index.js:374:26
    at Array.forEach (<anonymous>) {
  errno: -20,
  syscall: 'open',
  code: 'ENOTDIR',
  path: '[REDACTED]/frontend/src/images/logo.svg/index.js'
}
```

**Comment by steveswork** [comment]
This tool is for loading stylesheets. Please revisit the readme.md to see supported stylesheet extensions.

Sad to hear that you’re having issues with loading your svg module. Could you provide the framework and the error you got when loading the svg module without the tool?

**Comment by gugahoi** [comment]
The svg is imported by my component tho. Are you saying I need to remove all imports that are not css?

**Comment by gugahoi** [comment]
By the way, I am using create react app.

**Comment by steveswork** [comment]
To understand what’s happening, could you provide the codebase that you’re using the tool for?
